---
- include: create_users.yml

- include: sysctl.yml

- include: harden_dns.yml

- include: remove_kernel_modules.yml

- include: install_ntp.yml

- include: cron_apt.yml
  tags:
    - reboot

- include: apply_grsec_lock.yml
  tags:
    - reboot
    - grsec

- name: disable swap space
  command: swapoff -a
